AlaskaAirlines/auro-button

- README.md
- examples/create-react-app-example.md
- package.json
- src/package.json
**Fixes:** issue with miscommunication of ODS dependencies  
The scope of the changes was to address issues with hard dependencies versus peer dependencies, as well as update README documentation to address set up issues. 
See the summary statement.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and …
> update package json dependencies and address readme issues

- .gitignore
- .travis.yml
- README.md
- docs/TECH_DETAILS.md
- gulpfile.js
- package-lock.json
- package.json
**Fixes:** #17
This update will change the npm build process to include new pre-process alt import SCSS files. This update takes into consideration post-processing issues with using the `:host` selector outside of the component's context. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
-- Orion Design System Team
> update alternate output CSS for direct button CSS build sans local processing

- .travis.yml
- README.md
- demo/index.html
- package-lock.json
- package.json
- src/dancing-dots.json
- src/ods-button.js
- src/shape.json
- src/style.scss
This pull request will address issues raised in issue #19, as well as introduce a new prop type `condensed` to allow for reduced padding when the button is presented in narrow columns. 
**Fixes:** #19
In the previous state, there was no response for when the button was in a narrow space and there was more text in the button than the UI would allow for. In conjunction with this work, it seemed applicable to update the button API to allow for manual use of this narrow presentation. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is …
> Narrow buttons

- README.md
- docs/CALLBACK.md
- package-lock.json
- package.json
- src/ods-button.js
**Fixes:** #11
Scope of this update is to propose a solution for passing a click event into the outer component and passing that event into the scope of the component itself. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
-- Orion Design System Team
> Update component to support external events

- package-lock.json
- package.json
- src/ods-button.js
Update to support focus-visible polyfill and realignment of dependencies. 
This update address a service update to support OWCSS support for focus-visible. With the inclusion of the focus-visible library into the scope of the component, this will enhance the experience of visually impaired users as well as not present this same enhancement to users who are not impaired. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require …
> feat: add focus-visable ux a11y feature

- README.md
- index.js
- package.json
Simplifies the import statement required by consumers of this component.
Using a [barrel file](https://medium.com/@klauskpm/do-a-barrel-export-aa5b79b76b05) (see `index.js`), we are able to simplify the import statement required by consumers of this component in other applications.
Current:
`import "@alaskaairux/ods-button/dist/ods-button";`
Proposed:
`import "@alaskaairux/ods-button"`
It is important to note that the barrel file in this branch exports `*` from `./dist/ods-button`. Everything inside `./dist/ods-button` is available on scope of `@alaskaairux/ods-button`. If it's preferable to follow a whitelist model or allow other components to be exported on the `@alaskaair/ods-button` namespace, we can modify the barrel file to export certain components by writing `export { component1, …
> Simplify import statement required by consumers

- demo/index.html
- package-lock.json
- src/ods-button-light.js
- src/ods-button.js
Adds a light dom button component
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
-- Orion Design System Team
> feat: add light dom button

- .gitignore
- demo/index.html
- demo/sass/style.scss
- package-lock.json
- package.json
- src/auro-component-base.js
- src/style-auro.scss
AuroSupport branch code review/refactor
> refactor: code review refactor

- README.md
**Fixes:** #52 
PR fixes 404 issues with links in the README
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._ 
-- Orion Design System Team
> Address 404 in README

- README.md
- demo/index.html
- docs/api.md
- package-lock.json
- package.json
- src/auro-button-light.js
- src/auro-button.js
- src/style.scss
- test/auro-button.test.js
**Fixes:** #65 
Adding Icon Support to the button component. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this …
> auro-button: Icon support

- README.md
readme change only.
*Fixes: incorrect url for cdn assets
> Corrected typo on the cdn url

- demo/demo.md
- demo/index.html
- package-lock.json
- package.json
- src/auro-button.js
- src/style.scss
**Fixes:** #88
This change adds a new loading state which utilizes auro-loader. This `loading` state is meant to be used in instances where a button event can not yet take place due to a background process that is currently running.
Disabled state has changed how it applies opacity - rather than a general button opacity, the border, background and font colors are converted to an RGBA value with the same opacity in it - this allows for the loader to not have an opacity even when the button is disabled.
While the button is in the `loading` state the button text is hidden and `auro-loader` is rendered over the hidden text centered vertically and horizontally.
**By submitting this Pull Request, I confirm that my contribution is made under the terms …
> feat: add new loading state

- docs/accessibility.md
- package-lock.json
**Fixes:** #155
Added design accessibility notes.
> docs: add design accessibility guidelines

- docs/api.md
- src/auro-button.js
**Fixes:** #190
Adds the `auroButton-ready` event and fires it on `firstUpdated()`.
> feat(ready): notify readiness of the component #190

- .github/workflows/testPublish.yml
**Fixes:** #190
Semantic Release version needed to be bumped to v3 for testPublish workflow to work.
> fix(release): update semantic release version #190

- demo/demo.md
- docs/api.md
- package-lock.json
- src/auro-button.js
- src/style.scss
**Fixes:** #199 
This PR reflects the creation of the icon only button, along with the necessary styles and example documentation for the new feature.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission …
> feat(icononly): add icon only version of component #199

- .github/workflows/auroAssign.yml
**Resolves:** #218
Changes to be committed:
modified:   .github/workflows/auroAssign.yml
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and …
> build(assign): update automated assignment workflow #218

- src/auro-button.js
**Fixes:** #223
update lit class import referecnes
> fix(lit): update references to lit classes #223

- demo/api.md
- docs/api.md
- package-lock.json
- src/auro-button.js
**Fixes:** #225
Add css parts to the elements within the shadow DOM of `auro-button`.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …
> Add css parts to shadow DOM content

- .github/workflows/publishDemo.yml
Add the release surge demo workflow so future PRs generate a surge demo
> docs(demo): add surge demo creation workflow

- src/auro-button.js
**Fixes:** #233 
Add a css class to the `span` wrapping around the content of the button.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and …
> add class to span wrapping around content

- apiExamples/custom.html
- demo/index.html
- demo/index.md
- docs/partials/index.md
- index.js
- package-lock.json
Add custom registration example to index page
> perf(docs): add custom registration example to index page

- src/style.scss
Remove border affect from flat variant
> fix(flat): remove focus border from flat variant

- .eslintrc
- eslint.config.mjs
- package-lock.json
- package.json
**Resolves:** # (issue, if applicable)
Update all packages including the design tokens and eslint config
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the …
> Update design token version and eslint config

- src/auro-button.js
- src/colors.scss
**Resolves:** #252
Update the flat variant to use the new ui-secondary tokens and cleanup the disabled+hover style code.
-- Auro Design …
> Jbaker/use UI secondary tokens for flat

- src/colors.scss
**Resolves:** # (issue, if applicable)
Correct colors that made the UI wrong for the ondark `variant="flat"` button
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation …
> Update ondark flat variant colors

- src/style.scss
**Resolves:** #256
Remove styles that applied a hover UI to an auro-button in a disabled state
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …
> Remove disabled hover UI
